######## WORDPRESS

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress
spec:
  serviceName: "wordpress"
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: ft_service/wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress
  namespace: default
spec:
  loadBalancerIP: 192.168.99.103
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - port: 5050
    protocol: TCP
    targetPort: 5050
  selector:
    app: wordpress
