apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: wordpress
spec:
  serviceName: "wordpress"
  selector:
    matchLabels:
      app: wordpress
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: ft_service/wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
