apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: wordpress
spec:
  serviceName: "wordpress"
  selector:
    matchLabels:
      app: wordpress
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: ft_service/wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050

---

apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: wordpress
  name: wordpress
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.241
  externalTrafficPolicy: Cluster
  ports:
  - port: 5050
    protocol: TCP
    targetPort: 5050
  selector:
    app: wordpress
