# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: wordpress
  name: wordpress
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.241
  externalTrafficPolicy: Cluster
  ports:
  - port: 5050
    protocol: TCP
    targetPort: 5050
  selector:
    app: wordpress

