######## GRAFANA

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
spec:
  serviceName: "grafana"
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: ft_service/grafana
        imagePullPolicy: Never
        env:
        - name: SECRET_NAME
          valueFrom:
            secretKeyRef:
              name: user-credential 
              key: name 
        - name: SECRET_PASS
          valueFrom:
            secretKeyRef:
              name: user-credential 
              key: pass
        ports:
        - containerPort: 3000 

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: default
spec:
  loadBalancerIP: 192.168.99.102
  type: LoadBalancer
  ports:
  - name: port-1
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
