apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: nginx
spec:
  serviceName: "nginx"
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ft_service/nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 22
        - containerPort: 80
        - containerPort: 443
        env:
        - name: SECRET_NAME
          valueFrom:
            secretKeyRef:
              name: user-credential
              key: name
        - name: SECRET_PASS
          valueFrom:
            secretKeyRef:
              name: user-credential
              key: pass

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/address-pools: nginx-ip
  labels:
    app: nginx
spec:
  loadBalancerIP: 192.168.99.150
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - name: ssh
    port: 22
  - name: http
    port: 80
  - name: https
    port: 443

