apiVersion: v1
kind: PersistentVolume
metadata:
  name: influx-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/influx"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  - name: influx-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxdb
  name: influxdb
  namespace: default
spec:
  type: ClusterIP
  ports:
  - name: port-1
    port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: influxdb

---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: influxdb
spec:
  serviceName: "influxdb"
  selector:
    matchLabels:
      app: influxdb
  replicas: 1 
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      volumes:
      - name: influx-pv-storage
        persistentVolumeClaim:
          claimName: influx-pv-claim
      containers:
      - name: influxdb
        image: ft_service/influxdb
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
        volumeMounts:
        - mountPath: "/mnt/influx"
          name: influx-pv-storage
