apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: influxdb
spec:
  serviceName: "influxdb"
  selector:
    matchLabels:
      app: influxdb
  replicas: 1 
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: ft_service/influxdb
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
        volumeMounts:
        - name: influxdb-db
          mountPath: /mnt/db
        - name: influxdb-influx
          mountPath: /mnt/influx
      volumes:
      - name: influxdb-db
      - name: influxdb-influx
