apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: ftps
spec:
  serviceName: "ftps"
  selector:
    matchLabels:
      app: ftps
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ft_service/ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        volumeMounts:
        - name: ftps-data
          mountPath: /mnt/ftps_data
      volumes:
      - name: ftps-data
