apiVersion: v1
kind: Service
metadata:
  labels:
    app: ftps
  name: ftps
  annotations:
    metallb.universe.tf/address-pool: ftps-ip
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - name: port-20
    port: 20 
  - name: port-21
    port: 21
  - name: port-data
    port: 30000
  selector:
    app: ftps

---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: ftps
spec:
  serviceName: "ftps"
  selector:
    matchLabels:
      app: ftps
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ft_service/ftps
        imagePullPolicy: Never
        ports:
         - containerPort: 21
         - containerPort: 20
         - containerPort: 30000
        volumeMounts:
        - name: ftps-data
          mountPath: /mnt/ftps-data
      volumes:
      - name: ftps-data
