# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-07-09T07:19:54Z"
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
  labels:
    app: ftps
  name: ftps-deployment
  namespace: default
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - name: port-1
    port: 21
    protocol: TCP
    targetPort: 21
  selector:
    app: ftps
  sessionAffinity: None
